package com.justin.spring.web.app;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.justin.spring.web.app.util.User;
import com.justin.spring.web.app.util.WageSlip;
import com.justin.spring.web.app.util.WageSlipRepository;

/**
 * Loads the requested pay slip from the database.
 * @author Justin Alderson
 *
 */
@Controller
public class PaySlipController {
	
	@Autowired//This will get the bean called userRep which is auto generated by spring..
	private WageSlipRepository userRep;
	private ArrayList<WageSlip> wages = new ArrayList<>();
	private static final Logger log = LoggerFactory.getLogger(PaySlipController.class);

	 @RequestMapping(value="/paySlip", method=RequestMethod.POST)
	    public String tempTest(@RequestParam(value="month", required=true, defaultValue="")String month, String employeeName, User user,
	    		Model model,HttpServletRequest request) {
			log.info("\n\nSession infos" + request.getSession().getId() + "\n\n");
		 	if(user != null) {
		 		
		 			String userName = user.getUser();
		 			log.info("\n\nString name " + userName+ "\n\n");
					boolean inDatabase = false;
					WageSlip thisMonth = null;
					wages = (ArrayList<WageSlip>) getAllWages();
					
					for(WageSlip w : wages) {
						log.info("\n\nWageSlips: " + w.getName() + " " + w.getMonth() + "\n\n");
						if(userName.equals(w.getName()) & month.equals(w.getMonth())) {
							inDatabase = true;
							thisMonth = w;
							break;
						}
					}
					if(inDatabase) {
						model.addAttribute("employee", employeeName);
					    model.addAttribute("user", user);
				        model.addAttribute("month", month);
				        model.addAttribute("hoursWorked", thisMonth.getHoursWorked());
				        model.addAttribute("overtimeWorked", thisMonth.getOvertimeWorked());
				        model.addAttribute("base", thisMonth.getBasePay());
				        model.addAttribute("overtime", thisMonth.getOvertime());
				        model.addAttribute("shift", thisMonth.getShift());
				        model.addAttribute("regularity", thisMonth.getRegularity());
				        model.addAttribute("health", thisMonth.getHealth());
				        model.addAttribute("tax", thisMonth.getTax());
				        model.addAttribute("total", thisMonth.getTotalPay());
				        model.addAttribute("actual", thisMonth.getActualPay());
						   return "paySlip";
					}else {
						 return "unPaid";
					}
		 	}
		 
	      return "invalidUser";
	}
	 
	//Helper method to get all entries in wages table..
	private @ResponseBody Iterable<WageSlip> getAllWages(){
			return userRep.findAll();
	}
}
